hook.Add("AddToolMenuTabs", "LRPGamemode", function()
	spawnmenu.AddToolTab('LocalRP', '#LocalRP', 'icon16/brick.png')
	spawnmenu.AddToolMenuOption("LocalRP", "Client Options", "Client LocalRP Gamemode", "Gamemode", "", "", function(pnl)
		pnl:Help('Клиентские настройки режима LocalRP')
		pnl:CheckBox('Надпись "Толкнуть" у прицела', 'lrp_pushtext')

		pnl:Help('\nНастройки рации')
		pnl:KeyBinder('Кнопка активации рации', 'cl_lrp_radio_key')
	end)
	spawnmenu.AddToolMenuOption("LocalRP", "Server Options", "Server LocalRP Gamemode", "Gamemode", "", "", function(pnl)
		pnl:ClearControls()
		pnl:AddControl('label', {Text = "Серверные настройки режима LocalRP"})
		pnl:AddControl('textbox', {Label = 'Время возрождения', Command = 'lrp_respawntime'})
		pnl:AddControl('checkbox', {Label = 'Перелом ноги', Command = 'lrp_legbreak'})
		pnl:AddControl('checkbox', {Label = 'Урон при утоплении в воде', Command = 'lrp_drowning'})
	end)
end)