
lrp_view.options.label=First-person view options
lrp_view.options.toggle=View toggle
lrp_view.options.lock_toggle=View lock
lrp_view.options.lock_max=Max lock (looking down)
lrp_view.options.crosshair=Crosshair
lrp_view.options.crosshair_color=Crosshair color