
lrp_view.options.label=First-person view options
lrp_view.options.toggle=View toggle
lrp_view.options.lock_toggle=View lock
lrp_view.options.lock_max=Max lock (looking down)
lrp_view.options.crosshair=Crosshair
lrp_view.options.crosshair_color=Crosshair color
lrp_view.options.mod_title=Modifier
lrp_view.options.mod_disabled=Disabled

lrp_view.ui.shader_warn.title=Warning: LocalRP - View
lrp_view.ui.shader_warn.text=BodyCam shader requires "Simple Custom Shaders" addon\n\nYou can install it at the link below:
lrp_view.ui.shader_warn.link=Open "Simple Custom Shaders" in the browser