
lrp_guns.options.label_cl=Guns client options
lrp_guns.options.sight_res=Sight resolution

lrp_guns.ammo.air=Air cartridges
lrp_guns.ammo.large=Large caliber
lrp_guns.ammo.shotgun=Shot
lrp_guns.ammo.small=Small caliber

lrp_guns.weapons.air_pistol=Air Pistol
lrp_guns.weapons.air_revolver=Air Revolver
lrp_guns.weapons.air_shotgun=Air Shotgun
lrp_guns.weapons.air_smg=Air SMG