
lrp_view.options.label=Настройки вида от первого лица
lrp_view.options.toggle=Вид от первого лица
lrp_view.options.lock_toggle=Блокировка вида
lrp_view.options.lock_max=Максимальная блокировка (смотря вниз)
lrp_view.options.crosshair=Прицел
lrp_view.options.crosshair_color=Цвет прицела
lrp_view.options.mod_title=Модификатор
lrp_view.options.mod_disabled=Выключено

lrp_view.ui.shader_warn.title=Предупреждение: LocalRP - View
lrp_view.ui.shader_warn.text=Для эффекта BodyCam требуется аддон "Simple Custom Shaders"\n\nВы можете установить по ссылке ниже:
lrp_view.ui.shader_warn.link=Открыть "Simple Custom Shaders" в браузере