
lrp_view.options.label=Настройки вида от первого лица
lrp_view.options.toggle=Вид от первого лица
lrp_view.options.lock_toggle=Блокировка вида
lrp_view.options.lock_max=Максимальная блокировка (смотря вниз)
lrp_view.options.crosshair=Прицел
lrp_view.options.crosshair_color=Цвет прицела